
on:
  name: Deploy to  production Amazon ECS
  push:
    branches:
    - main
  jobs:

  build:
    name: build image
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

     - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ecr-web-image
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -docker build -t ecr-web-imag .
        docker push 787952688011.dkr.ecr.us-east-1.amazonaws.com/ecr-web-image:latest
      